steps:
  # - label: ":docker: build image"
  #   command: docker build -t "plugin-demo:${BUILDKITE_BUILD_NUMBER}" .
  #   plugins:
  #     - wiz#v1.3.1:
  #         scan-type: 'docker'
  #         image-address: "plugin-demo:${BUILDKITE_BUILD_NUMBER}"
  #         api-secret-env: WIZ_SECRET
  
  # - wait

  - label: ":terraform: terraform scan"
    command: echo "Scanning Terraform"
    plugins:
      - /Users/jeremy/dev/plugins/wiz-buildkite-plugin#iac-scan-fix:
          scan-type: iac
          iac-type: Terraform
          api-secret-env: WIZ_SECRET
          path: './main.tf'
          parameter-files: './variables.tf'
          

      