steps:
  - label: ":docker: build image"
    command: docker build -t "plugin-demo:${BUILDKITE_BUILD_NUMBER}" .
    plugins:
      - wiz#v1.3.0:
          scan-type: 'docker'
          image-address: "plugin-demo:${BUILDKITE_BUILD_NUMBER}"
          api-secret-env: WIZ_SECRET
      